site_name: My Docs
repo_url: https://github.com/gchristodo/Documentation_Test
site_url: https://gchristodo.github.io/Documentation_Test
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
    watch:
      - code
nav:
  - Home: Home/index.md

